### PR TITLE
Update zero copy message ctors to handle any callable accepting void* as a deleter

### PR DESCRIPTION
**Pull request by rodgert**
Support, for instance, lambdas, in addition to static delete functions

### CODE REVIEW

**Comment by oliora** [comment]
@rodgert unfortunately this is not enough.
# Moving of deleter should be added to move ctor/move assignment.
# Using `this` as a hint does not survive after moving of message. I can't find any good solution instead. I'll try to think more about this tomorrow.

**Comment by rodgert** [comment]
Whoah, big font!

Good catch, I don't have an obvious solution to this yet...

**Comment by oliora** [comment]
I have a solution but I'm not very happy with it.

We should keep two versions of ctor with deleter:
1. Accepting deleter functor. One should be forwarded to heap-allocated storage.
2. Accepting two void ptrs (function and hint) that are just passed to ZeroMQ to avoid any extra allocations

```
class message {
...
template<class Deleter>
static void call_deleter(void *data, void *deleter_)
{
    auto deleter = static_cast<Deleter *>(deleter_);
    (*deleter)(data);
    delete deleter;
}

template<class Deleter>
message(noncopytag_t, void *buf, size_t size, Deleter &&deleter_)
{
    auto deleter = new Deleter(std::forward<Deleter>(deleter_)); // allocate on heap
    auto rc = zmq_msg_init_data(..., &call_deleter<Deleter>, deleter);
    // delete deleter on error...
}

message(noncopytag_t, void *buf, size_t size, zmq_free_fn *ffn, void *hint); // just forwards everything to zmq_msg_init_data(), w/o extra allocations
```

**Comment by rodgert** [comment]
Yeah, I think this leads us back to why the deleter is part of
std::unique_ptr<> type, and ctor arg for std::shared_ptr<>, the latter must
incur an allocation anyway, the former should be as cheap as possible.

**Comment by oliora** [comment]
Here we just can not have deleter to be a part of `azmq::message` because deleter lifetime is controlled by ZeroMQ rather than by `azmq::message`.

**Comment by oliora** [comment]
Prepare a fix: https://github.com/oliora/azmq/commit/6f34a32559b3f603fcbb006d30678ccbb429057f
Gonna make a pull request after #106 is merged.

**Pull request merged**
