### PR TITLE
Add support for extensible async_ overloads

### PR DESCRIPTION
**Pull request by aboseley**
Completion tokens were first released in 2013 as part of Boost v1.54.  In Boost v1.70 a helper template function ```async_initiate``` was added to ASIO to assist with the initiation of async operations. This PR adds 3 new azmq async functions using this helper while leaving the existing API unchanged.

### CODE REVIEW

**Comment by cbrl** [comment]
Is there any blocking issue for this? It would be quite convenient to have these features. I can attest that tests pass on Windows 11 x64, in addition to the Ubuntu and Mac OS checks from the CI workflow.

**Comment by aboseley** [comment]
There's no blocking issue, I made the change a while back and was looking for feedback from users.

**Comment by cbrl** [comment]
Alright. I'm all for it in that case. It's not difficult to write external helper functions which handle the executor binding and `async_initiate` business, but it would be convenient to have it supported at the library level, and would let a user write code in the same style they would with the ASIO-provided I/O objects.

**Comment by jbbjarnason** [comment]
could this be merged or is this WIP ?

**Pull request merged**
