### PR TITLE
Make library compatible with c++20.

### PR DESCRIPTION
**Pull request by slepasteur**
Fix issue #170

### CODE REVIEW

**Comment by aboseley** [comment]
Is there something else that needs to be done for this PR to be accepted?

**Comment by sphaero** [comment]
I think more active maintainers that follow [C4](https://rfc.zeromq.org/spec/42/). As you are probably using this library I could add you to the maintainers! Let me know.

**Comment by aboseley** [comment]
I'd be happy to help.

**Comment by sphaero** [comment]
You should have received an invite. Please read the [C4](https://rfc.zeromq.org/spec/42/) rfc so you understand the process. If you have any questions please let me know.

**Comment by aboseley** [comment]
Should we close a few of these issues that are already fixed on master?

**Comment by sphaero** [comment]
Go ahead. We don't really deal with issues formally. Only PR's. So it's really up to the users what to do with issues. Most repos have a stale bot monitoring issues

**Pull request merged**
